### ISSUE TITLE
Report 27/12

### ISSUE THREAD

**Issue by Mihai-CV** [Mihai-CV/Canvas-Fighting-Game#1]
Lo que hare hoy principalmente será planificar el proyecto, documentarme acerca de lo visto en clase sobre canvas y los elementos básicos que necesitare implementar en el proyecto, como el escenario, plataformas, movimiento direccional, saltos y sprites.

**Comment by amargopastor** [comment]
Estupendo @Mihai-CV ! No te olvides de incluir todos tus avances, documentación, issues etc en el report 28/12
