### ISSUE TITLE
Recorrer una sola vez el bucle de animaciones

### ISSUE THREAD

**Issue by Mihai-CV** [Mihai-CV/Canvas-Fighting-Game#12]
Básicamente lo que hablamos en clase, para cosas especificas como los golpes o animaciones de ganar la partida, perder o cualquier cosa similar necesito que el array de sprites para dicha animación se recorra una sola vez al pulsar el botón. Lo que yo uso es una idea dada por Marc que es una especie de bucle mediante un frameCount que se activa cada vez que se entra en el método drow y recorrer los sprites de la animación continuamente, pero en estos casos concretos de los que estoy hablando no me sirve y no se como adaptarlo. He probado con un apaño poniendo un setTimeout en la acción del keyboard_event_up() para crear una especie de delay y que se pueda ver toda la animación. Aun así es muy precario y además de que no se llega a ver del todo bien definida la animación no me sirve para interactuar con las próximas incorporaciones del juego. Todo esto esta en el archivo Fighter.ts

**Comment by Alvaro-Lucas** [comment]
He conseguido (de forma muy chapucera), que la animación del puñetazo se ejecute una vez, pero el problema es que lo hace a velocidad de la luz 😅. Esto no lo considero una solución ni de lejos, pero dejo aquí la idea por sí sirve de algo.
<img width="387" alt="image" src="https://user-images.githubusercontent.com/33863370/147828901-3b422e97-523f-4825-8811-f60fcac1f15e.png">
<img width="133" alt="image" src="https://user-images.githubusercontent.com/33863370/147828917-b6e08d92-5a3c-472d-b431-25c47025b888.png">

He cambiado el tipo de parámetro que recibe `keyboard_event_down` a `keyboardEvent` en vez de un String para poder utilizar el método `repeat`.
