### ISSUE TITLE
No me funciona github page

### ISSUE THREAD

**Issue by Mihai-CV** [Mihai-CV/Canvas-Fighting-Game#14]
He implementado los nuevos scripts que nos enseñaste en clase y también la carpeta .github, probé de las dos formas, tanto a mano como la forma automática y no me funciona, me muestra la pagina en blanco.

**Comment by amargopastor** [comment]
@Mihai-CV has modificado el root por docs? Te sale algún mensaje de error en la consola o similar?

**Comment by Mihai-CV** [comment]
Lo he cambiado todo como enseñaste en clase y nada. La primera vez que hice el build me salia un mensaje de error relacionado a una linea del .json que era algo de un main, lo quite y a partir de ahí funcionó y ya no me salia ningun mensaje de error, aun asi me sale la pantalla en blanco en el github page

**Comment by amargopastor** [comment]
Parece que no detecta los archivos de tu proyecto:
![Screenshot 2021-12-31 at 13 29 45](https://user-images.githubusercontent.com/73180300/147823551-0913ee4c-a930-4725-beb3-5fcb6a4f37a7.png)

¿Quizás no estemos indicando correctamente la ruta pública?

```json
"ghbuild": "parcel build --dist-dir docs --public-url /Canvas-Fighting-Game index.html",
```

**Comment by Mihai-CV** [comment]
Justo! Era eso. Gracias por la ayuda, no se porque pensaba que ahí tenia que poner el nombre de mi archivo en local y no el nombre del repo de github 😅
